// <auto-generated />
using System;
using DataAccessLayer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fatherhood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strikes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fatherhood = "Catz",
                            Name = "Artur",
                            Strikes = 0,
                            Surname = "Kupchinsky",
                            Title = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Fatherhood = "Galerovich",
                            Name = "Vasya",
                            Strikes = 0,
                            Surname = "Pupkin",
                            Title = "Engineer"
                        },
                        new
                        {
                            Id = 3,
                            Fatherhood = "Massonovich",
                            Name = "Grisha",
                            Strikes = 1,
                            Surname = "Zadneprivodniy",
                            Title = "Tester"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShiftEnds")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShiftStarts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Hours = 8,
                            ShiftEnds = new DateTime(2022, 5, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftStarts = new DateTime(2022, 5, 31, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            Hours = 8,
                            ShiftEnds = new DateTime(2022, 5, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftStarts = new DateTime(2022, 5, 31, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            Hours = 1,
                            ShiftEnds = new DateTime(2022, 5, 31, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftStarts = new DateTime(2022, 5, 31, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftDAO", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeDAO", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeDAO", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
